name: React Native Test With Cypress

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: expo start
          web: expo start --web
          wait-on: 'http://localhost:8081'
          wait-on-timeout: 60